<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

function commerce_product_redirect_to_view_form_commerce_product_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
// Check if we are on the product edit form.
  if ($form_id == 'commerce_product_producto_b_sico_edit_form') {
  $form['actions']['submit']['#submit'][] = 'commerce_product_redirect_to_view_product_form_submit';
  }
}

function commerce_product_redirect_to_view_product_form_submit(array &$form, FormStateInterface $form_state) {
  $redirect_path = '/admin/commerce/products';
  $form_state->setRedirectUrl(Url::fromUserInput($redirect_path));
}
